name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 触发主分支推送事件时运行

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: gsap_cocktails
    concurrency:
      group: deploy
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: pnpm install
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
        
      - name: Setup pnpm config
        run: pnpm config set store-dir "$PNPM_CACHE_FOLDER"
        # Makes sure the pnpm store path exists (which is exactly what setup-node cares about)
      - name: Verify PNPM Cache Directory
        run: |
          PNPM_STORE_PATH="$( pnpm store path --silent )"
          if [ ! -d "$PNPM_STORE_PATH" ]; then
            echo "PNPM store directory does not exist, creating it."
            mkdir -p "$PNPM_STORE_PATH"
          else
            echo "PNPM store directory exists."
          fi
    
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'  # 根据你的项目需求选择合适的 Node.js 版本
          cache: pnpm           # 缓存 pnpm 安装的依赖

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies and Build project
        run:  pnpm install --frozen-lockfile && pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 上传 dist 文件夹
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.TOKEN }}

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.TOKEN }}
      #     publish_dir: ./dist     # 构建输出目录，默认是 dist
